version: '3'

vars:
  temp_dir: temp

tasks:
  checkout:
    desc: "Clone a Git repository into the '{{.temp_dir}}' directory"
    vars:
      repo_url: '{{.CLI_ARGS}}'
    cmds:
      - |
        if [ -d "{{.temp_dir}}" ]; then
          echo "'{{.temp_dir}}' directory exists. Clearing its contents."
          rm -rf {{.temp_dir}}/*
        else:
          echo "'{{.temp_dir}}' directory does not exist. Creating it."
          mkdir {{.temp_dir}}
        fi
      - |
        echo "Cloning the repository {{.repo_url}} into the '{{.temp_dir}}' directory."
        git clone {{.repo_url}} {{.temp_dir}}
    silent: false

  cleanup:
    desc: "Remove the '{{.temp_dir}}' directory"
    cmds:
      - |
        if [ -d "{{.temp_dir}}" ]; then
          echo "Removing the '{{.temp_dir}}' directory."
          rm -rf {{.temp_dir}}
        else:
          echo "'{{.temp_dir}}' directory does not exist. Nothing to remove."
        fi
    silent: false
